spring:
  application:
    name: rest
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
# 배포 환경에서는 꺼놓는게 권장
springdoc:
  api-docs:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:.env.dev[.properties]
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
# 개발 환경에서 사용
springdoc:
  api-docs:
    enabled: true
#    path: /v3/api-docs
  default-produces-media-type: application/json
#  swagger-ui:
#    path: /swagger-ui.html